"""followers

Revision ID: 01eb568fc83f
Revises: 63db46171805
Create Date: 2022-04-10 19:24:12.850288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01eb568fc83f'
down_revision = '63db46171805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
