"""new fields in user model

Revision ID: 63db46171805
Revises: 617e5e66f2db
Create Date: 2022-04-04 20:59:59.487548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63db46171805'
down_revision = '617e5e66f2db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
